#!/usr/bin/env python
"""
创建初始分类数据脚本
在迁移前创建必要的分类数据
"""
import os
import sys

# 添加项目根目录到Python路径
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

# 设置Django环境
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "wechat_survey.settings")

import django
django.setup()

from django.db import connection

# 初始分类数据
INITIAL_CATEGORIES = [
    ("basic", "基本信息"),
    ("satisfaction", "满意度"),
    ("feedback", "反馈建议"),
    ("product", "产品相关"),
    ("service", "服务相关"),
    ("other", "其他"),
]

def create_initial_categories():
    """创建初始分类数据的Django迁移脚本"""
    print("开始创建初始分类迁移...")
    
    # 创建一个迁移文件，用于添加初始分类数据
    migration_content = """
# Generated by Django %(django_version)s on %(datetime)s
from django.db import migrations


def create_initial_categories(apps, schema_editor):
    Category = apps.get_model('survey', 'Category')
    
    # 初始分类数据
    initial_categories = [
        {'name': '基本信息', 'slug': 'basic', 'description': '基本信息分类'},
        {'name': '满意度', 'slug': 'satisfaction', 'description': '满意度分类'},
        {'name': '反馈建议', 'slug': 'feedback', 'description': '反馈建议分类'},
        {'name': '产品相关', 'slug': 'product', 'description': '产品相关分类'},
        {'name': '服务相关', 'slug': 'service', 'description': '服务相关分类'},
        {'name': '其他', 'slug': 'other', 'description': '其他分类'},
    ]
    
    for category_data in initial_categories:
        Category.objects.get_or_create(
            slug=category_data['slug'],
            defaults=category_data
        )


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_category_alter_question_category'),
    ]

    operations = [
        migrations.RunPython(create_initial_categories),
    ]
"""
    
    import datetime
    import django
    
    # 生成迁移文件
    migration_filename = f"survey/migrations/0006_initial_categories.py"
    with open(migration_filename, 'w', encoding='utf-8') as f:
        f.write(migration_content % {
            'django_version': django.get_version(),
            'datetime': datetime.datetime.now().strftime('%Y-%m-%d %H:%M')
        })
    
    print(f"创建迁移文件: {migration_filename}")
    print("初始分类迁移创建完成!")

if __name__ == "__main__":
    create_initial_categories()
