"""
Django settings for wechat_survey project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# 导入django-environ用于环境变量管理
import environ

# 初始化environ
env = environ.Env(
    DEBUG=(bool, True),
    ALLOWED_HOSTS=(list, ['*']),
    DATABASE_URL=(str, 'sqlite:///db.sqlite3'),
    SECRET_KEY=(str, 'django-insecure-wa478o&xc3^6#_xo2c-h)sjyg%-0qtm#n(36jvsu+q=+)xr1b8'),
    WECHAT_APP_ID=(str, ''),
    WECHAT_APP_SECRET=(str, ''),
    USE_SSL=(bool, False),
    # MySQL数据库配置
    DB_NAME=(str, 'wechat_survey'),
    DB_USER=(str, 'wechat_survey_user'),
    DB_PASSWORD=(str, 'your-strong-db-password'),
    DB_HOST=(str, 'localhost'),
    DB_PORT=(str, '3306'),
)

# 从环境变量指定的.env文件加载配置，默认使用.env
env_file = os.environ.get('ENV_FILE', '.env')
environ.Env.read_env(os.path.join(Path(__file__).resolve().parent.parent, env_file))

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

# 允许访问的主机列表
ALLOWED_HOSTS = env('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'survey',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wechat_survey.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wechat_survey.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# 默认使用SQLite数据库（开发环境）
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MySQL数据库配置模板（生产环境使用）
# 取消注释并修改以下配置，或使用DATABASE_URL环境变量
"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', default='wechat_survey'),
        'USER': env('DB_USER', default='wechat_survey_user'),
        'PASSWORD': env('DB_PASSWORD', default='your-strong-db-password'),
        'HOST': env('DB_HOST', default='localhost'),
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'sql_mode': 'STRICT_TRANS_TABLES',
        },
    }
}
"""

# 也可以使用DATABASE_URL环境变量（优先级最高）
# 格式：mysql://user:password@host:port/dbname
if env('DATABASE_URL', default=None):
    DATABASES = {
        'default': env.db(),
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 国际化
LANGUAGE_CODE = 'zh-hans'  # 修改为中文
TIME_ZONE = 'Asia/Shanghai'  # 修改为上海时间
USE_I18N = True
USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 初始化PyMySQL，支持MySQL数据库（生产环境使用）
import pymysql
pymysql.install_as_MySQLdb()

# === 以下是微信问卷系统的额外配置 ===

# 微信配置
WECHAT_APP_ID = env('WECHAT_APP_ID')
WECHAT_APP_SECRET = env('WECHAT_APP_SECRET')

# 静态文件配置
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# 开发环境静态文件搜索目录
# 注意：这里只需要添加项目级别的静态目录
# 应用下的 static 目录 Django 会自动发现
STATICFILES_DIRS = [
    # 如果你有项目级别的静态文件，才需要添加
    # os.path.join(BASE_DIR, 'static'),
]


# 媒体文件配置（如果需要上传文件）
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 模板目录配置
TEMPLATES[0]['DIRS'] = [os.path.join(BASE_DIR, 'templates')]

# 会话配置（用于记录问卷状态）
SESSION_COOKIE_AGE = 86400  # 24小时
SESSION_SAVE_EVERY_REQUEST = True

# REST Framework 配置
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',  # 根据需求调整
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
    ]
}

# === 环境相关配置 ===

# SSL配置
USE_SSL = env('USE_SSL', default=False)

# 根据DEBUG状态应用不同的安全配置
if DEBUG:
    # 开发环境安全配置
    SECURE_SSL_REDIRECT = False
    CSRF_COOKIE_SECURE = False
    SESSION_COOKIE_SECURE = False
    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False
    
    # 开发环境允许所有主机访问
    ALLOWED_HOSTS = env('ALLOWED_HOSTS', default=['*'])
else:
    # 生产环境安全配置
    # SSL配置
    if USE_SSL:
        SECURE_SSL_REDIRECT = True
        CSRF_COOKIE_SECURE = True
        SESSION_COOKIE_SECURE = True
        SECURE_HSTS_SECONDS = 31536000
        SECURE_HSTS_INCLUDE_SUBDOMAINS = True
        SECURE_HSTS_PRELOAD = True
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    else:
        SECURE_SSL_REDIRECT = False
        CSRF_COOKIE_SECURE = False
        SESSION_COOKIE_SECURE = False
        SECURE_HSTS_SECONDS = 0
        SECURE_HSTS_INCLUDE_SUBDOMAINS = False
        SECURE_HSTS_PRELOAD = False
        SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'http')
    
    # 生产环境额外安全配置
    SECURE_CONTENT_TYPE_NOSNIFF = True  # 防止浏览器猜测内容类型
    SECURE_BROWSER_XSS_FILTER = True  # 启用浏览器XSS过滤器
    X_FRAME_OPTIONS = 'DENY'  # 防止点击劫持
    
    # 会话安全配置
    SESSION_COOKIE_HTTPONLY = True  # 防止JavaScript访问会话cookie
    SESSION_COOKIE_SAMESITE = 'Lax'  # 限制跨站点请求
    
    # CSRF安全配置
    CSRF_COOKIE_HTTPONLY = True  # 防止JavaScript访问CSRF cookie
    CSRF_COOKIE_SAMESITE = 'Lax'  # 限制跨站点请求
    
    # 生产环境必须指定具体的域名
    ALLOWED_HOSTS = env('ALLOWED_HOSTS', default=['your-domain.com', 'www.your-domain.com'])


