# Generated by Django 5.2 on 2025-12-03 11:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='问题内容')),
                ('question_type', models.CharField(choices=[('text', '文本题'), ('single_choice', '单选题'), ('multiple_choice', '多选题'), ('rating', '评分题'), ('date', '日期题')], max_length=50, verbose_name='问题类型')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('options', models.JSONField(blank=True, default=list, verbose_name='选项（JSON格式）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '问题',
                'verbose_name_plural': '问题',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='会话标识')),
                ('wechat_openid', models.CharField(blank=True, max_length=100, verbose_name='微信OpenID')),
                ('wechat_unionid', models.CharField(blank=True, max_length=100, verbose_name='微信UnionID')),
                ('wechat_nickname', models.CharField(blank=True, max_length=100, verbose_name='微信昵称')),
                ('submit_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('user_agent', models.TextField(blank=True, verbose_name='用户代理')),
                ('completion_time', models.IntegerField(default=0, verbose_name='完成用时（秒）')),
                ('respondent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='回答者')),
            ],
            options={
                'verbose_name': '回答记录',
                'verbose_name_plural': '回答记录',
                'ordering': ['-submit_time'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True, verbose_name='回答文本')),
                ('answer_choice', models.JSONField(blank=True, default=list, verbose_name='选择答案')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='回答时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='survey.question', verbose_name='问题')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='survey.response', verbose_name='所属回答')),
            ],
            options={
                'verbose_name': '答案',
                'verbose_name_plural': '答案',
            },
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='问卷标题')),
                ('description', models.TextField(blank=True, verbose_name='问卷描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
                ('start_date', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('require_wechat', models.BooleanField(default=False, verbose_name='必须微信打开')),
                ('allow_anonymous', models.BooleanField(default=True, verbose_name='允许匿名')),
                ('limit_per_user', models.IntegerField(default=1, verbose_name='每人提交限制')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='创建者')),
            ],
            options={
                'verbose_name': '问卷',
                'verbose_name_plural': '问卷',
            },
        ),
        migrations.AddField(
            model_name='response',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.survey', verbose_name='问卷'),
        ),
        migrations.AddField(
            model_name='question',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='survey.survey', verbose_name='所属问卷'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='二维码名称')),
                ('short_code', models.CharField(max_length=20, unique=True, verbose_name='短代码')),
                ('scan_count', models.IntegerField(default=0, verbose_name='扫描次数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='survey.survey', verbose_name='对应问卷')),
            ],
            options={
                'verbose_name': '二维码',
                'verbose_name_plural': '二维码',
            },
        ),
    ]
