# Generated by Django 5.2 on 2025-12-03 13:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_remove_question_options_alter_answer_question_option'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-created_at'], 'verbose_name': '问题', 'verbose_name_plural': '问题库'},
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_required',
        ),
        migrations.RemoveField(
            model_name='question',
            name='order',
        ),
        migrations.RemoveField(
            model_name='question',
            name='survey',
        ),
        migrations.AddField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='是否公开'),
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0, verbose_name='问题排序')),
                ('is_required', models.BooleanField(default=True, verbose_name='是否必填')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='survey.question', verbose_name='问题')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='survey_questions', to='survey.survey', verbose_name='所属问卷')),
            ],
            options={
                'verbose_name': '问卷问题关联',
                'verbose_name_plural': '问卷问题关联',
                'ordering': ['order'],
                'unique_together': {('survey', 'question')},
            },
        ),
    ]
