# Generated by Django 5.2 on 2025-12-03 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_alter_question_options_remove_question_is_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('basic', '基本信息'), ('satisfaction', '满意度'), ('feedback', '反馈建议'), ('product', '产品相关'), ('service', '服务相关'), ('other', '其他')], default='other', max_length=50, verbose_name='问题分类'),
        ),
    ]
