# Generated by Django 5.2 on 2025-12-03 14:42

from django.db import migrations, models


def create_initial_categories(apps, schema_editor):
    """创建初始分类数据"""
    Category = apps.get_model('survey', 'Category')
    
    # 初始分类数据
    initial_categories = [
        {'name': '基本信息', 'slug': 'basic', 'description': '基本信息分类'},
        {'name': '满意度', 'slug': 'satisfaction', 'description': '满意度分类'},
        {'name': '反馈建议', 'slug': 'feedback', 'description': '反馈建议分类'},
        {'name': '产品相关', 'slug': 'product', 'description': '产品相关分类'},
        {'name': '服务相关', 'slug': 'service', 'description': '服务相关分类'},
        {'name': '其他', 'slug': 'other', 'description': '其他分类'},
    ]
    
    for category_data in initial_categories:
        Category.objects.create(**category_data)


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_question_category'),
    ]

    operations = [
        # 创建Category模型表
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分类名称')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='分类标识')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分类描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否激活')),
            ],
            options={
                'verbose_name': '问题分类',
                'verbose_name_plural': '问题分类管理',
                'ordering': ['name'],
            },
        ),
        # 插入初始分类数据
        migrations.RunPython(create_initial_categories),
    ]
