# Generated by Django 5.2 on 2025-12-03 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0005_create_category_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='survey.category', verbose_name='问题分类'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(default='other', max_length=50, verbose_name='问题分类'),
        ),
    ]
