# Generated by Django 5.2 on 2025-12-03 14:44

from django.db import migrations


def populate_category_fk(apps, schema_editor):
    """将旧的category字段值转换为新的category_fk外键关联"""
    Question = apps.get_model('survey', 'Question')
    Category = apps.get_model('survey', 'Category')
    
    # 创建分类映射字典
    category_mapping = {
        'basic': 'basic',
        'satisfaction': 'satisfaction',
        'feedback': 'feedback',
        'product': 'product',
        'service': 'service',
        'other': 'other',
    }
    
    # 获取所有分类对象
    categories = {cat.slug: cat for cat in Category.objects.all()}
    
    # 更新每个问题的category_fk字段
    for question in Question.objects.all():
        old_category = question.category
        if old_category in category_mapping:
            slug = category_mapping[old_category]
            if slug in categories:
                question.category_fk = categories[slug]
                question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0006_question_category_fk_alter_question_category'),
    ]

    operations = [
        # 填充category_fk字段
        migrations.RunPython(populate_category_fk),
    ]
