# Generated by Django 5.2 on 2025-12-03 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_populate_category_fk'),
    ]

    operations = [
        # 1. 将旧的category字段重命名为category_old
        migrations.RenameField(
            model_name='question',
            old_name='category',
            new_name='category_old',
        ),
        # 2. 将category_fk字段重命名为category
        migrations.RenameField(
            model_name='question',
            old_name='category_fk',
            new_name='category',
        ),
        # 3. 移除旧的category_old字段
        migrations.RemoveField(
            model_name='question',
            name='category_old',
        ),
    ]
