# Generated by Django 5.2 on 2025-12-03 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_remove_question_category_fk_alter_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyquestion',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='survey.category', verbose_name='问题分类'),
        ),
    ]
