# Generated by Django 5.2 on 2025-12-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_surveyquestion_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveyquestion',
            name='category',
        ),
    ]
