# Generated by Django 5.2 on 2025-12-04 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_questiontemplate_questiontemplateitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiontemplateitem',
            name='template',
        ),
        migrations.RemoveField(
            model_name='questiontemplateitem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='questiontemplateitem',
            name='question',
        ),
        migrations.DeleteModel(
            name='QuestionTemplate',
        ),
        migrations.DeleteModel(
            name='QuestionTemplateItem',
        ),
    ]
