# Generated by Django 5.2 on 2025-12-23 07:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0013_remove_questiontemplateitem_template_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['response', 'question__survey_questions__order'], 'verbose_name': '答案', 'verbose_name_plural': '答案'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question', 'order'], 'verbose_name': '选项', 'verbose_name_plural': '选项'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'ordering': ['-created_at'], 'verbose_name': '二维码', 'verbose_name_plural': '二维码'},
        ),
        migrations.AlterModelOptions(
            name='survey',
            options={'ordering': ['-created_at'], 'verbose_name': '问卷', 'verbose_name_plural': '问卷'},
        ),
        migrations.AlterModelOptions(
            name='surveyquestion',
            options={'ordering': ['survey', 'order'], 'verbose_name': '问卷问题关联', 'verbose_name_plural': '问卷问题关联'},
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_choice',
            field=models.JSONField(blank=True, default=list, help_text='用于选择题的回答（JSON格式）', verbose_name='选择答案'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='answer_text',
            field=models.TextField(blank=True, help_text='用于文本题的回答', verbose_name='回答文本'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='可选，填写分类的详细说明', null=True, verbose_name='分类描述'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, help_text='只有激活的分类才能使用', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='分类的唯一名称', max_length=100, unique=True, verbose_name='分类名称'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='用于URL的分类标识', max_length=100, unique=True, verbose_name='分类标识'),
        ),
        migrations.AlterField(
            model_name='option',
            name='label',
            field=models.CharField(help_text='显示给用户看到的选项文本', max_length=200, verbose_name='选项标签'),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.IntegerField(default=0, help_text='数字越小，排序越靠前', verbose_name='选项排序'),
        ),
        migrations.AlterField(
            model_name='option',
            name='value',
            field=models.CharField(help_text='用于存储和识别的值（英文或数字）', max_length=100, verbose_name='选项值'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='name',
            field=models.CharField(help_text='便于识别的二维码名称', max_length=100, verbose_name='二维码名称'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='scan_count',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='扫描次数'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='short_code',
            field=models.CharField(db_index=True, help_text='用于生成短链接的唯一代码', max_length=20, unique=True, verbose_name='短代码'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(blank=True, help_text='选择问题的分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='survey.category', verbose_name='问题分类'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, help_text='公开的问题可以被所有用户使用', verbose_name='是否公开'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', '文本题'), ('single_choice', '单选题'), ('multiple_choice', '多选题'), ('rating', '评分题'), ('date', '日期题')], db_index=True, max_length=50, verbose_name='问题类型'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='输入问题的完整描述', verbose_name='问题内容'),
        ),
        migrations.AlterField(
            model_name='response',
            name='completion_time',
            field=models.IntegerField(default=0, help_text='从开始填写到提交的总用时（秒）', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(86400)], verbose_name='完成用时（秒）'),
        ),
        migrations.AlterField(
            model_name='response',
            name='respondent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_responses', to=settings.AUTH_USER_MODEL, verbose_name='回答者'),
        ),
        migrations.AlterField(
            model_name='response',
            name='session_key',
            field=models.CharField(blank=True, help_text='用于匿名用户的会话标识', max_length=100, verbose_name='会话标识'),
        ),
        migrations.AlterField(
            model_name='response',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='提交时间'),
        ),
        migrations.AlterField(
            model_name='response',
            name='wechat_openid',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信OpenID'),
        ),
        migrations.AlterField(
            model_name='response',
            name='wechat_unionid',
            field=models.CharField(blank=True, db_index=True, max_length=100, verbose_name='微信UnionID'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='allow_anonymous',
            field=models.BooleanField(default=True, help_text='是否允许未登录用户提交问卷', verbose_name='允许匿名'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='description',
            field=models.TextField(blank=True, help_text='可选，填写问卷的详细说明', verbose_name='问卷描述'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='问卷结束的时间，留空表示不限制', null=True, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='只有激活的问卷才能被访问', verbose_name='是否激活'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='limit_per_user',
            field=models.IntegerField(default=1, help_text='每个用户最多可提交的次数', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='每人提交限制'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='require_wechat',
            field=models.BooleanField(default=False, help_text='如果启用，只能通过微信访问问卷', verbose_name='必须微信打开'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='问卷开始的时间，留空表示立即开始', null=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='survey',
            name='title',
            field=models.CharField(help_text='输入问卷的标题，最多200个字符', max_length=200, verbose_name='问卷标题'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='category',
            field=models.ForeignKey(blank=True, help_text='可覆盖问题的原始分类', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='survey_questions', to='survey.category', verbose_name='问题分类'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='is_required',
            field=models.BooleanField(default=True, help_text='如果启用，用户必须回答这个问题才能提交问卷', verbose_name='是否必填'),
        ),
        migrations.AlterField(
            model_name='surveyquestion',
            name='order',
            field=models.IntegerField(default=0, help_text='数字越小，排序越靠前', verbose_name='问题排序'),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('response', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('question', 'value')},
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['response', 'question'], name='survey_answ_respons_fdcaf0_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_active'], name='survey_cate_slug_ae1c28_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['question', 'order'], name='survey_opti_questio_57d4aa_idx'),
        ),
        migrations.AddIndex(
            model_name='qrcode',
            index=models.Index(fields=['short_code'], name='survey_qrco_short_c_f960e4_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_type', 'is_public'], name='survey_ques_questio_1a3f50_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['category', 'created_at'], name='survey_ques_categor_7fb731_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['survey', 'submit_time'], name='survey_resp_survey__18f24c_idx'),
        ),
        migrations.AddIndex(
            model_name='response',
            index=models.Index(fields=['wechat_openid', 'survey'], name='survey_resp_wechat__05619e_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['is_active', 'start_date', 'end_date'], name='survey_surv_is_acti_133cb1_idx'),
        ),
        migrations.AddIndex(
            model_name='survey',
            index=models.Index(fields=['created_by', 'created_at'], name='survey_surv_created_de9fc1_idx'),
        ),
        migrations.AddIndex(
            model_name='surveyquestion',
            index=models.Index(fields=['survey', 'order'], name='survey_surv_survey__81a8d3_idx'),
        ),
    ]
