# Generated by Django 5.2 on 2025-12-27 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorizationCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='授权码')),
                ('is_used', models.BooleanField(default=False, verbose_name='是否已使用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '授权码',
                'verbose_name_plural': '授权码',
                'db_table': 'rpi_authorization_code',
            },
        ),
        migrations.CreateModel(
            name='RPIQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='问题内容')),
                ('question_order', models.IntegerField(verbose_name='问题顺序')),
                ('category', models.CharField(max_length=50, verbose_name='问题类别')),
            ],
            options={
                'verbose_name': 'RPI测试问题',
                'verbose_name_plural': 'RPI测试问题',
                'db_table': 'rpi_question',
                'ordering': ['question_order'],
            },
        ),
        migrations.CreateModel(
            name='RPIUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=100, null=True, verbose_name='昵称')),
                ('gender', models.CharField(blank=True, choices=[('male', '男'), ('female', '女'), ('other', '其他')], max_length=10, null=True, verbose_name='性别')),
                ('age_range', models.CharField(blank=True, choices=[('18-24', '18-24岁'), ('25-29', '25-29岁'), ('30-34', '30-34岁'), ('35-39', '35-39岁'), ('40-49', '40-49岁'), ('50+', '50岁以上')], max_length=10, null=True, verbose_name='年龄段')),
                ('relationship_status', models.CharField(blank=True, choices=[('single', '单身'), ('in_relationship', '恋爱中'), ('married', '已婚'), ('divorced', '离婚'), ('widowed', '丧偶')], max_length=20, null=True, verbose_name='恋爱状态')),
                ('test_type', models.CharField(blank=True, choices=[('self', '给自己测'), ('partner', '为恋人测')], max_length=10, null=True, verbose_name='测试类型')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('authorization_code', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rpi_calculator.authorizationcode', verbose_name='授权码')),
            ],
            options={
                'verbose_name': 'RPI测试用户',
                'verbose_name_plural': 'RPI测试用户',
                'db_table': 'rpi_user',
            },
        ),
        migrations.CreateModel(
            name='RPITestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(verbose_name='总分')),
                ('score_level', models.CharField(max_length=20, verbose_name='得分等级')),
                ('summary', models.TextField(verbose_name='结果总结')),
                ('detailed_analysis', models.TextField(verbose_name='详细分析')),
                ('suggestions', models.TextField(verbose_name='建议')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_result', to='rpi_calculator.rpiuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RPI测试结果',
                'verbose_name_plural': 'RPI测试结果',
                'db_table': 'rpi_test_result',
            },
        ),
        migrations.CreateModel(
            name='RPIAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(verbose_name='得分')),
                ('answer_text', models.TextField(verbose_name='答案内容')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rpi_calculator.rpiquestion', verbose_name='问题')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='rpi_calculator.rpiuser', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'RPI测试答案',
                'verbose_name_plural': 'RPI测试答案',
                'db_table': 'rpi_answer',
            },
        ),
    ]
